// Code generated by protoc-gen-go. DO NOT EDIT.
// source: myfile.proto

package myfile

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValueRequest struct {
	Sub1                 int32    `protobuf:"varint,1,opt,name=sub1,proto3" json:"sub1,omitempty"`
	Sub2                 int32    `protobuf:"varint,2,opt,name=sub2,proto3" json:"sub2,omitempty"`
	Sub3                 int32    `protobuf:"varint,3,opt,name=sub3,proto3" json:"sub3,omitempty"`
	Sub4                 int32    `protobuf:"varint,4,opt,name=sub4,proto3" json:"sub4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValueRequest) Reset()         { *m = ValueRequest{} }
func (m *ValueRequest) String() string { return proto.CompactTextString(m) }
func (*ValueRequest) ProtoMessage()    {}
func (*ValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f71277a7d1198f3, []int{0}
}

func (m *ValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueRequest.Unmarshal(m, b)
}
func (m *ValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueRequest.Marshal(b, m, deterministic)
}
func (m *ValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueRequest.Merge(m, src)
}
func (m *ValueRequest) XXX_Size() int {
	return xxx_messageInfo_ValueRequest.Size(m)
}
func (m *ValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValueRequest proto.InternalMessageInfo

func (m *ValueRequest) GetSub1() int32 {
	if m != nil {
		return m.Sub1
	}
	return 0
}

func (m *ValueRequest) GetSub2() int32 {
	if m != nil {
		return m.Sub2
	}
	return 0
}

func (m *ValueRequest) GetSub3() int32 {
	if m != nil {
		return m.Sub3
	}
	return 0
}

func (m *ValueRequest) GetSub4() int32 {
	if m != nil {
		return m.Sub4
	}
	return 0
}

type ValueReponse struct {
	Finalvalue           int32    `protobuf:"varint,1,opt,name=finalvalue,proto3" json:"finalvalue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValueReponse) Reset()         { *m = ValueReponse{} }
func (m *ValueReponse) String() string { return proto.CompactTextString(m) }
func (*ValueReponse) ProtoMessage()    {}
func (*ValueReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f71277a7d1198f3, []int{1}
}

func (m *ValueReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueReponse.Unmarshal(m, b)
}
func (m *ValueReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueReponse.Marshal(b, m, deterministic)
}
func (m *ValueReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueReponse.Merge(m, src)
}
func (m *ValueReponse) XXX_Size() int {
	return xxx_messageInfo_ValueReponse.Size(m)
}
func (m *ValueReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueReponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValueReponse proto.InternalMessageInfo

func (m *ValueReponse) GetFinalvalue() int32 {
	if m != nil {
		return m.Finalvalue
	}
	return 0
}

func init() {
	proto.RegisterType((*ValueRequest)(nil), "ValueRequest")
	proto.RegisterType((*ValueReponse)(nil), "ValueReponse")
}

func init() { proto.RegisterFile("myfile.proto", fileDescriptor_5f71277a7d1198f3) }

var fileDescriptor_5f71277a7d1198f3 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xad, 0x4c, 0xcb,
	0xcc, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x8a, 0xe3, 0xe2, 0x09, 0x4b, 0xcc, 0x29,
	0x4d, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0x29, 0x2e, 0x4d, 0x32,
	0x94, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0xb3, 0xa1, 0x62, 0x46, 0x12, 0x4c, 0x70, 0x31,
	0x23, 0xa8, 0x98, 0xb1, 0x04, 0x33, 0x5c, 0xcc, 0x18, 0x2a, 0x66, 0x22, 0xc1, 0x02, 0x17, 0x33,
	0x51, 0xd2, 0x83, 0x9b, 0x5f, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc7, 0xc5, 0x95, 0x96, 0x99,
	0x97, 0x98, 0x53, 0x06, 0x12, 0x84, 0xda, 0x82, 0x24, 0x62, 0x64, 0xcd, 0xc5, 0xef, 0x9c, 0x5e,
	0x90, 0x18, 0xef, 0x9c, 0x98, 0x93, 0x5c, 0x9a, 0x93, 0x58, 0x92, 0x5f, 0x24, 0xa4, 0xc1, 0xc5,
	0xe1, 0x9e, 0x5a, 0x02, 0x36, 0x45, 0x88, 0x57, 0x0f, 0xd9, 0xb5, 0x52, 0x70, 0x2e, 0xd8, 0xf0,
	0x24, 0x36, 0xb0, 0x9f, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x90, 0x8a, 0xde, 0x77, 0xe3,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Cgpa_CalculatorClient is the client API for Cgpa_Calculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Cgpa_CalculatorClient interface {
	GetValue(ctx context.Context, in *ValueRequest, opts ...grpc.CallOption) (*ValueReponse, error)
}

type cgpa_CalculatorClient struct {
	cc *grpc.ClientConn
}

func NewCgpa_CalculatorClient(cc *grpc.ClientConn) Cgpa_CalculatorClient {
	return &cgpa_CalculatorClient{cc}
}

func (c *cgpa_CalculatorClient) GetValue(ctx context.Context, in *ValueRequest, opts ...grpc.CallOption) (*ValueReponse, error) {
	out := new(ValueReponse)
	err := c.cc.Invoke(ctx, "/Cgpa_Calculator/GetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Cgpa_CalculatorServer is the server API for Cgpa_Calculator service.
type Cgpa_CalculatorServer interface {
	GetValue(context.Context, *ValueRequest) (*ValueReponse, error)
}

// UnimplementedCgpa_CalculatorServer can be embedded to have forward compatible implementations.
type UnimplementedCgpa_CalculatorServer struct {
}

func (*UnimplementedCgpa_CalculatorServer) GetValue(ctx context.Context, req *ValueRequest) (*ValueReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}

func RegisterCgpa_CalculatorServer(s *grpc.Server, srv Cgpa_CalculatorServer) {
	s.RegisterService(&_Cgpa_Calculator_serviceDesc, srv)
}

func _Cgpa_Calculator_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Cgpa_CalculatorServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cgpa_Calculator/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Cgpa_CalculatorServer).GetValue(ctx, req.(*ValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cgpa_Calculator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Cgpa_Calculator",
	HandlerType: (*Cgpa_CalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetValue",
			Handler:    _Cgpa_Calculator_GetValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "myfile.proto",
}
